In [6]:
import numpy as np
import pandas as pd
import seaborn as sns
import matplotlib.pyplot as plt

In [7]:
activity=pd.read_csv('dailyActivity_merged.csv')
activity

,Id,ActivityDate,TotalSteps,TotalDistance,TrackerDistance,LoggedActivitiesDistance,VeryActiveDistance,ModeratelyActiveDistance,LightActiveDistance,SedentaryActiveDistance,VeryActiveMinutes,FairlyActiveMinutes,LightlyActiveMinutes,SedentaryMinutes,Calories
0,1503960366,4/12/2016,13162,8.500000,8.500000,0.0,1.88,0.55,6.06,0.00,25,13,328,728,1985
1,1503960366,4/13/2016,10735,6.970000,6.970000,0.0,1.57,0.69,4.71,0.00,21,19,217,776,1797
2,1503960366,4/14/2016,10460,6.740000,6.740000,0.0,2.44,0.40,3.91,0.00,30,11,181,1218,1776
3,1503960366,4/15/2016,9762,6.280000,6.280000,0.0,2.14,1.26,2.83,0.00,29,34,209,726,1745
4,1503960366,4/16/2016,12669,8.160000,8.160000,0.0,2.71,0.41,5.04,0.00,36,10,221,773,1863
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
935,8877689391,5/8/2016,10686,8.110000,8.110000,0.0,1.08,0.20,6.80,0.00,17,4,245,1174,2847
936,8877689391,5/9/2016,20226,18.250000,18.250000,0.0,11.10,0.80,6.24,0.05,73,19,217,1131,3710
937,8877689391,5/10/2016,10733,8.150000,8.150000,0.0,1.35,0.46,6.28,0.00,18,11,224,1187,2832
938,8877689391,5/11/2016,21420,19.559999,19.559999,0.0,13.22,0.41,5.89,0.00,88,12,213,1127,3832
939,8877689391,5/12/2016,8064,6.120000,6.120000,0.0,1.82,0.04,4.25,0.00,23,1,137,770,1849

In [8]:
calories=pd.read_csv('dailyCalories_merged.csv')
calories

             Id ActivityDay  Calories
0    1503960366   4/12/2016      1985
1    1503960366   4/13/2016      1797
2    1503960366   4/14/2016      1776
3    1503960366   4/15/2016      1745
4    1503960366   4/16/2016      1863
..          ...         ...       ...
935  8877689391    5/8/2016      2847
936  8877689391    5/9/2016      3710
937  8877689391   5/10/2016      2832
938  8877689391   5/11/2016      3832
939  8877689391   5/12/2016      1849

[940 rows x 3 columns]

In [9]:
intensity=pd.read_csv('dailyIntensities_merged.csv')
intensity

,Id,ActivityDay,SedentaryMinutes,LightlyActiveMinutes,FairlyActiveMinutes,VeryActiveMinutes,SedentaryActiveDistance,LightActiveDistance,ModeratelyActiveDistance,VeryActiveDistance
0,1503960366,4/12/2016,728,328,13,25,0.00,6.06,0.55,1.88
1,1503960366,4/13/2016,776,217,19,21,0.00,4.71,0.69,1.57
2,1503960366,4/14/2016,1218,181,11,30,0.00,3.91,0.40,2.44
3,1503960366,4/15/2016,726,209,34,29,0.00,2.83,1.26,2.14
4,1503960366,4/16/2016,773,221,10,36,0.00,5.04,0.41,2.71
...,...,...,...,...,...,...,...,...,...,...
935,8877689391,5/8/2016,1174,245,4,17,0.00,6.80,0.20,1.08
936,8877689391,5/9/2016,1131,217,19,73,0.05,6.24,0.80,11.10
937,8877689391,5/10/2016,1187,224,11,18,0.00,6.28,0.46,1.35
938,8877689391,5/11/2016,1127,213,12,88,0.00,5.89,0.41,13.22
939,8877689391,5/12/2016,770,137,1,23,0.00,4.25,0.04,1.82

In [10]:
steps=pd.read_csv('dailySteps_merged.csv')
steps

             Id ActivityDay  StepTotal
0    1503960366   4/12/2016      13162
1    1503960366   4/13/2016      10735
2    1503960366   4/14/2016      10460
3    1503960366   4/15/2016       9762
4    1503960366   4/16/2016      12669
..          ...         ...        ...
935  8877689391    5/8/2016      10686
936  8877689391    5/9/2016      20226
937  8877689391   5/10/2016      10733
938  8877689391   5/11/2016      21420
939  8877689391   5/12/2016       8064

[940 rows x 3 columns]

In [11]:
heartrate=pd.read_csv('heartrate_seconds_merged.csv')
heartrate

                 Id                  Time  Value
0        2022484408  4/12/2016 7:21:00 AM     97
1        2022484408  4/12/2016 7:21:05 AM    102
2        2022484408  4/12/2016 7:21:10 AM    105
3        2022484408  4/12/2016 7:21:20 AM    103
4        2022484408  4/12/2016 7:21:25 AM    101
...             ...                   ...    ...
2483653  8877689391  5/12/2016 2:43:53 PM     57
2483654  8877689391  5/12/2016 2:43:58 PM     56
2483655  8877689391  5/12/2016 2:44:03 PM     55
2483656  8877689391  5/12/2016 2:44:18 PM     55
2483657  8877689391  5/12/2016 2:44:28 PM     56

[2483658 rows x 3 columns]

In [12]:
sleep=pd.read_csv('sleepDay_merged.csv')
sleep

,Id,SleepDay,TotalSleepRecords,TotalMinutesAsleep,TotalTimeInBed
0,1503960366,4/12/2016 12:00:00 AM,1,327,346
1,1503960366,4/13/2016 12:00:00 AM,2,384,407
2,1503960366,4/15/2016 12:00:00 AM,1,412,442
3,1503960366,4/16/2016 12:00:00 AM,2,340,367
4,1503960366,4/17/2016 12:00:00 AM,1,700,712
...,...,...,...,...,...
408,8792009665,4/30/2016 12:00:00 AM,1,343,360
409,8792009665,5/1/2016 12:00:00 AM,1,503,527
410,8792009665,5/2/2016 12:00:00 AM,1,415,423
411,8792009665,5/3/2016 12:00:00 AM,1,516,545
412,8792009665,5/4/2016 12:00:00 AM,1,439,463

In [13]:
weight=pd.read_csv('weightlogInfo_merged.csv')
weight

,Id,Date,WeightKg,WeightPounds,Fat,BMI,IsManualReport,LogId
0,1503960366,5/2/2016 11:59:59 PM,52.599998,115.963147,22.0,22.650000,True,1462233599000
1,1503960366,5/3/2016 11:59:59 PM,52.599998,115.963147,NaN,22.650000,True,1462319999000
2,1927972279,4/13/2016 1:08:52 AM,133.500000,294.317120,NaN,47.540001,False,1460509732000
3,2873212765,4/21/2016 11:59:59 PM,56.700001,125.002104,NaN,21.450001,True,1461283199000
4,2873212765,5/12/2016 11:59:59 PM,57.299999,126.324875,NaN,21.690001,True,1463097599000
...,...,...,...,...,...,...,...,...
62,8877689391,5/6/2016 6:43:35 AM,85.000000,187.392923,NaN,25.440001,False,1462517015000
63,8877689391,5/8/2016 7:35:53 AM,85.400002,188.274775,NaN,25.559999,False,1462692953000
64,8877689391,5/9/2016 6:39:44 AM,85.500000,188.495234,NaN,25.610001,False,1462775984000
65,8877689391,5/11/2016 6:51:47 AM,85.400002,188.274775,NaN,25.559999,False,1462949507000
66,8877689391,5/12/2016 6:42:53 AM,84.000000,185.188300,NaN,25.139999,False,1463035373000

In [14]:
# Date column clean & same format 
activity['ActivityDate'] = pd.to_datetime(activity['ActivityDate'])
calories['ActivityDay'] = pd.to_datetime(calories['ActivityDay'])
intensity['ActivityDay'] = pd.to_datetime(intensity['ActivityDay'])
steps['ActivityDay'] = pd.to_datetime(steps['ActivityDay'])
sleep['SleepDay'] = pd.to_datetime(sleep['SleepDay'])
weight['Date'] = pd.to_datetime(weight['Date'])
heartrate['Time'] = pd.to_datetime(heartrate['Time'])

C:\Users\Shree\AppData\Local\Temp\ipykernel_8180\3375527365.py:6: UserWarning: Could not infer format, so each element will be parsed individually, falling back to `dateutil`. To ensure parsing is consistent and as-expected, please specify a format.
  sleep['SleepDay'] = pd.to_datetime(sleep['SleepDay'])
C:\Users\Shree\AppData\Local\Temp\ipykernel_8180\3375527365.py:7: UserWarning: Could not infer format, so each element will be parsed individually, falling back to `dateutil`. To ensure parsing is consistent and as-expected, please specify a format.
  weight['Date'] = pd.to_datetime(weight['Date'])

In [15]:
# change heartrate 
heartrate['Date'] = heartrate['Time'].dt.date

daily_hr = heartrate.groupby(['Id', 'Date'])['Value'].mean().reset_index()
daily_hr.rename(columns={'Value': 'AvgHeartRate'}, inplace=True)

daily_hr['Date'] = pd.to_datetime(daily_hr['Date'])

In [16]:
# merge all dataset
merged_df = (
    activity
    .merge(
        calories,
        left_on=["Id", "ActivityDate"],
        right_on=["Id", "ActivityDay"],
        how="left"
    )
    .merge(
        steps,
        on=["Id", "ActivityDay"],
        how="left"
    )
    .merge(
        intensity,
        on=["Id", "ActivityDay"],
        how="left"
    )
    .merge(
        sleep,
        left_on=["Id", "ActivityDate"],
        right_on=["Id", "SleepDay"],
        how="left"
    )
    .merge(
        weight,
        left_on=["Id", "ActivityDate"],
        right_on=["Id", "Date"],
        how="left"
    )
    .merge(
        daily_hr,
        left_on=["Id", "ActivityDate"],
        right_on=["Id", "Date"],
        how="left"
    )
)

In [17]:
merged_df.head()

,Id,ActivityDate,TotalSteps,TotalDistance,TrackerDistance,LoggedActivitiesDistance,VeryActiveDistance_x,ModeratelyActiveDistance_x,LightActiveDistance_x,SedentaryActiveDistance_x,...,TotalTimeInBed,Date_x,WeightKg,WeightPounds,Fat,BMI,IsManualReport,LogId,Date_y,AvgHeartRate
0,1503960366,2016-04-12,13162,8.50,8.50,0.0,1.88,0.55,6.06,0.0,...,346.0,NaT,NaN,NaN,NaN,NaN,NaN,NaN,NaT,NaN
1,1503960366,2016-04-13,10735,6.97,6.97,0.0,1.57,0.69,4.71,0.0,...,407.0,NaT,NaN,NaN,NaN,NaN,NaN,NaN,NaT,NaN
2,1503960366,2016-04-14,10460,6.74,6.74,0.0,2.44,0.40,3.91,0.0,...,NaN,NaT,NaN,NaN,NaN,NaN,NaN,NaN,NaT,NaN
3,1503960366,2016-04-15,9762,6.28,6.28,0.0,2.14,1.26,2.83,0.0,...,442.0,NaT,NaN,NaN,NaN,NaN,NaN,NaN,NaT,NaN
4,1503960366,2016-04-16,12669,8.16,8.16,0.0,2.71,0.41,5.04,0.0,...,367.0,NaT,NaN,NaN,NaN,NaN,NaN,NaN,NaT,NaN

In [33]:
# 1. First use the daily activity data and find the unique id of all the users.
activity['Id'].unique()

array([1503960366, 1624580081, 1644430081, 1844505072, 1927972279,
       2022484408, 2026352035, 2320127002, 2347167796, 2873212765,
       3372868164, 3977333714, 4020332650, 4057192912, 4319703577,
       4388161847, 4445114986, 4558609924, 4702921684, 5553957443,
       5577150313, 6117666160, 6290855005, 6775888955, 6962181067,
       7007744171, 7086361926, 8053475328, 8253242879, 8378563200,
       8583815059, 8792009665, 8877689391])

In [ ]:
# 2. Then find the number of days they use their fitness tracker.
user_days = merged_df.groupby('Id')['ActivityDate'].nunique().reset_index()
user_days.columns = ['Id', 'TotalDaysUsed']

user_days.head()

In [ ]:
# 3. Use this data to group all the users into Active(>20), moderate(>10,<20) and light(<10) users.
def user_type(days):
    if days > 20:
        return 'Active'
    elif days >= 10:
        return 'Moderate'
    else:
        return 'Light'

user_days['UserType'] = user_days['TotalDaysUsed'].apply(user_type)
user_days.head()

In [ ]:
# 4. After that find out the mean distance traveled by each user
mean_distance=merged_df.groupby('Id')['TotalDistance'].mean().reset_index()
mean_distance.columns=['Id','MeanDistance']
mean_distance.head()

In [ ]:
# 5. Use this mean distance to group each user into Pro,Intermediate and beginner.(set criteria by yourself)
def distance_level(dist):
    if dist>10:
        return 'Pro'
    elif dist>=5:
        return 'Intermediate'
    else:
        return 'Beginner'
mean_distance['Level']=mean_distance['MeanDistance'].apply(distance_level)
mean_distance.head()

In [ ]:
# 6. Then find out the total steps traveled by each user
total_steps=merged_df.groupby('Id')['TotalSteps'].sum().reset_index()
total_steps.columns=['ID','TotalSteps']
total_steps.head()

In [ ]:
# 7 -> Total calories burn per user
total_calories=merged_df.groupby('Id')['Calories_x'].sum().reset_index()
total_calories.columns=['ID','TotalCalories']
total_calories.head()

In [ ]:
# 8 -> Active minutes per user
activity_minutes = merged_df.groupby('Id')[[
    'VeryActiveMinutes_x',
    'FairlyActiveMinutes_x',
    'LightlyActiveMinutes_x'
]].sum().reset_index()

activity_minutes.head()

In [ ]:
# 9. Repeat all these tasks (1 to 8) with respect to distinct dates
# (a) Unique users per date
user_per_date=merged_df.groupby('ActivityDate')['Id'].nunique().reset_index()
user_per_date.columns=['Date','TotalUsers']
user_per_date.head()

In [ ]:
# (b) Steps per date
steps_per_date=merged_df.groupby('ActivityDate')['TotalSteps'].nunique().reset_index()
steps_per_date.columns=['Date','TotalSteps']
steps_per_date.head()

In [ ]:
# (c) Calories per date
calories_per_date=merged_df.groupby('ActivityDate')['Calories_x'].sum().reset_index()
calories_per_date.head()

In [ ]:
# (d) Activity minutes per date
minutes_per_date = merged_df.groupby('ActivityDate')[[
    'VeryActiveMinutes_x',
    'FairlyActiveMinutes_x',
    'LightlyActiveMinutes_x'
]].sum().reset_index()

minutes_per_date.head()

In [ ]:
# 10. Use this filtered data to create charts and graphs for better visualization.
# 1️⃣ User Type distribution
user_days['UserType'].value_counts().plot(kind='bar', title='User Activity Type')
plt.show()

In [ ]:
# 2️⃣ Mean distance category
mean_distance['Level'].value_counts().plot(kind='pie',autopct='%1.1f%%',title='Mean Distance')
plt.show()

In [ ]:
# 3️⃣ Steps over time
steps_per_date.plot(x='Date', y='TotalSteps', figsize=(10,4))
plt.show()

In [ ]:
# 4️⃣ Calories over time
calories_per_date.plot(x='ActivityDate', y='Calories_x', figsize=(10,4))
plt.show()

In [ ]:
# 5️⃣ Activity minutes bar chart
activity_minutes[['VeryActiveMinutes',
                   'FairlyActiveMinutes',
                   'LightlyActiveMinutes']].mean().plot(kind='bar')
plt.show()

In [ ]:
# 11. Users with high steps but low calories
user_summary = merged_df.groupby('Id')[['StepTotal','Calories_x']].mean()

high_steps_low_cal = user_summary[
    (user_summary['StepTotal'] > user_summary['StepTotal'].quantile(0.75)) &
    (user_summary['Calories_x'] < user_summary['Calories_x'].quantile(0.25))
]
high_steps_low_cal

# Insight: Steps high hone ke baad bhi calories low ⇒ low intensity walking / slow pace

In [ ]:
# 12. Steps vs Calories relationship
merged_df[['StepTotal','Calories_x']].corr()

# Insight:  Correlation perfect nahi hota ⇒ calories sirf steps se decide nahi hoti

In [ ]:
# 13. Weekend vs Weekday active users
merged_df['day_type'] = merged_df['ActivityDate'].dt.day_name()
merged_df['is_weekend'] = merged_df['day_type'].isin(['Saturday','Sunday'])

weekend_activity = merged_df.groupby(['Id','is_weekend'])['StepTotal'].mean().unstack()
weekend_activity

# Insight:  Weekend-active users = office lifestyle indicator

In [ ]:
# 14. VeryActiveMinutes vs Distance
merged_df[['VeryActiveMinutes_x','TotalDistance']].corr()

# Insight: High intensity ≠ long distance (HIIT, gym workouts)

In [ ]:
# 15. High calories but low steps
user_summary[
    (user_summary['Calories_x'] > user_summary['Calories_x'].quantile(0.75)) &
    (user_summary['StepTotal'] < user_summary['StepTotal'].quantile(0.25))
]

# Insight: Non-step workouts (strength training, cycling)

In [ ]:
# 16. Sleep duration vs next-day steps
merged_df['sleep_hours'] = merged_df['TotalMinutesAsleep'] / 60
merged_df[['sleep_hours','StepTotal']].corr()

# Insight: Better sleep ⇒ better activity next day

In [ ]:
# 17. Poor sleep & lightly active minutes
merged_df.groupby(pd.cut(merged_df['sleep_hours'], [0,5,7,10]))['LightlyActiveMinutes_x'].mean()

# Insight:  Kam sleep ⇒ zyada light activity (low energy)

In [ ]:
# 18. Most consistent users (low variance)
consistency = merged_df.groupby('Id')['StepTotal'].std().sort_values().reset_index()
consistency.head()

# Insight: Low std = disciplined lifestyle

In [ ]:
# 19. Most irregular users
consistency.tail()

# Insight: Fitness inconsistency / motivation drop

In [ ]:
# 20. Weight change vs calories
weight_cal = weight.merge(merged_df.groupby('Id')['Calories_x'].mean(), on='Id', how='left')
weight_cal[['WeightKg','Calories_x']].corr()

# Insight:  Calories alone ≠ weight loss guarantee

In [ ]:
# 21. Calories high but weight gain
weight_cal[weight_cal['WeightKg'] > weight_cal['WeightKg'].mean()]

# Insight: Diet surplus or muscle gain

In [ ]:
# 22. Which users convert physical activity into calories most efficiently over the entire observation period (cumulative, not daily)?
efficiency = merged_df.groupby('Id').apply(
    lambda x: x['Calories_x'].sum() / x['TotalDistance'].sum()
)
efficiency.sort_values(ascending=False).reset_index()

# Insight: Cumulative efficiency avoids daily noise and highlights long-term metabolic efficiency, a concept applicable to any performance dataset.

In [ ]:
# 23. Is improvement in sleep followed by improvement in activity with a time lag (lagged relationship)?
sleep_trend = merged_df.groupby('Id')['sleep_hours'].rolling(5).mean()
activity_trend = merged_df.groupby('Id')['StepTotal'].rolling(5).mean()

sleep_trend.shift(3).corr(activity_trend)

# Insight: Health and behavior changes rarely act instantly. Lag analysis shows causal sequencing, a strong advanced EDA skill.

In [ ]:
# 24. For which users are calories driven more by intensity than by steps?
merged_df.groupby('Id').apply(
    lambda x: x['Calories_x'].corr(x['VeryActiveMinutes_x']) -
              x['Calories_x'].corr(x['StepTotal'])
).sort_values(ascending=False).reset_index()

# Insight: Separates intensity-driven vs volume-driven users — a reusable behavioral analytics pattern.

In [ ]:
# 25. Is weight change explained better by activity, calories, or sleep?
weight_merged = weight.merge(
    merged_df.groupby('Id')[['Calories_x','sleep_hours','VeryActiveMinutes_x']].mean(),
    on='Id'
)

weight_merged.corr()['WeightKg'].reset_index()

# Insight: Moves beyond assumptions and quantifies dominant explanatory signals.

In [ ]:
# 26. Which users violate the “more steps = more calories” assumption?
merged_df.groupby('Id')['Calories_x'].corr(merged_df['StepTotal']).reset_index()

# Insight: Weak or negative correlations reveal non-linear physiology or behavioral anomalies.

In [ ]:
# 27. Are users consistently active, or only active on specific days of the week?
merged_df.groupby(['Id', merged_df['ActivityDate'].dt.day_name()])['VeryActiveMinutes_x'].mean()

# Insight: Distinguishes routine-based behavior from event-based behavior.

In [ ]:
# 28. Which users have stable calorie burn but unstable step counts?
stds = merged_df.groupby('Id')[['Calories_x','StepTotal']].std()
stds[stds['Calories_x'] < stds['StepTotal']]

# Insight: Evaluates metric reliability — crucial in any sensor-based dataset.

In [ ]:
# 29. Do users compensate poor sleep with higher workout intensity?
merged_df[merged_df['sleep_hours'] < 6].groupby('Id')['VeryActiveMinutes_x'].mean().reset_index()

# Insight: Reveals risky compensation behavior, common in high-pressure lifestyles.

In [19]:
# 30. Which users improve fitness but not body weight?
fitness_change = merged_df.groupby('Id')['VeryActiveMinutes_x'].apply(
    lambda x: x.iloc[-1] - x.iloc[0]
)

fitness_change[fitness_change > 0]


# Insight: Demonstrates that fitness ≠ weight loss, correcting a common analytical mistake.

Id
4057192912    3
6775888955    2
Name: VeryActiveMinutes_x, dtype: int64

In [21]:
# 31. Which users show early enthusiasm followed by burnout?
merged_df.groupby('Id')['StepTotal'].apply(
    lambda x: x.iloc[:7].mean() - x.iloc[-7:].mean()
)

# Insight:  Classic churn pattern, transferable to product analytics.

Id
1503960366    1186.000000
1624580081    4257.714286
1644430081    2114.142857
1844505072    5128.428571
1927972279     117.142857
2022484408    2310.428571
2026352035   -3293.714286
2320127002    1310.285714
2347167796    2612.000000
2873212765     371.285714
3372868164    1071.857143
3977333714    -935.714286
4020332650   -2593.571429
4057192912       0.000000
4319703577   -1609.142857
4388161847   -3763.571429
4445114986    -898.000000
4558609924    -180.857143
4702921684   -1658.714286
5553957443     937.142857
5577150313    5922.857143
6117666160     781.428571
6290855005    2019.000000
6775888955    2408.571429
6962181067     388.714286
7007744171    1624.571429
7086361926   -4661.285714
8053475328    3649.000000
8253242879    1442.428571
8378563200    4519.428571
8583815059   -2664.857143
8792009665     792.428571
8877689391    3393.285714
Name: StepTotal, dtype: float64

In [24]:
# 32. Can we create a user-level “Activity Stability Index” using a custom function, and identify the most stable users?

def activity_stability(group):
    step_std = group['TotalSteps'].std()
    active_std = group['VeryActiveMinutes_x'].std()
    
    # lower std = higher stability
    stability_score = 1 / (step_std + active_std + 1)
    return stability_score

stability_index = (
    merged_df
    .groupby('Id')
    .apply(activity_stability)
    .sort_values(ascending=False)
)

stability_index.head(10).reset_index()


# Insight:  This index captures behavioral consistency, not performance. High stability users are ideal for long-term habit modeling, even if their absolute activity is moderate.

C:\Users\Shree\AppData\Local\Temp\ipykernel_8180\989548968.py:14: DeprecationWarning: DataFrameGroupBy.apply operated on the grouping columns. This behavior is deprecated, and in a future version of pandas the grouping columns will be excluded from the operation. Either pass `include_groups=False` to exclude the groupings or explicitly select the grouping columns after groupby to silence this warning.
  .apply(activity_stability)

           Id         0
0  1927972279  0.000826
1  2873212765  0.000651
2  3372868164  0.000540
3  4445114986  0.000513
4  2320127002  0.000443
5  8792009665  0.000429
6  4558609924  0.000422
7  4057192912  0.000371
8  1844505072  0.000368
9  2022484408  0.000353

In [28]:
# 33. Can we classify daily behavior into intensity profiles using a custom mapping function?
def activity_profile(row):
    if row['VeryActiveMinutes_x'] > row['LightlyActiveMinutes_x']:
        return 'Intensity-Driven'
    elif row['LightlyActiveMinutes_x'] > row['SedentaryMinutes_x']:
        return 'Light-Active'
    else:
        return 'Sedentary-Dominant'

merged_df['activity_profile'] = merged_df.apply(activity_profile, axis=1)

profile_distribution = (
    merged_df
    .groupby('Id')['activity_profile']
    .value_counts(normalize=True)
)

profile_distribution.head(10).reset_index()

# Insight : This shows how users spend their energy, not how much. Such categorical profiling is highly reusable in customer behavior analytics.

           Id    activity_profile  proportion
0  1503960366  Sedentary-Dominant    1.000000
1  1624580081  Sedentary-Dominant    0.967742
2  1624580081    Intensity-Driven    0.032258
3  1644430081  Sedentary-Dominant    1.000000
4  1844505072  Sedentary-Dominant    1.000000
5  1927972279  Sedentary-Dominant    1.000000
6  2022484408  Sedentary-Dominant    1.000000
7  2026352035  Sedentary-Dominant    0.967742
8  2026352035        Light-Active    0.032258
9  2320127002  Sedentary-Dominant    1.000000

In [35]:
# 34. Can we build a custom “Recovery Efficiency Score” using sleep and next-day activity with a lambda function?
def recovery_efficiency(group):
    group = group.sort_values('Date_y')
    
    next_day_steps = group['TotalSteps'].shift(-1)
    sleep = group['TotalMinutesAsleep']
    
    efficiency = (next_day_steps / (sleep + 1)).mean()
    return efficiency

recovery_score = (
    merged_df
    .groupby('Id')
    .apply(recovery_efficiency)
    .sort_values(ascending=False)
)

recovery_score.head(10).reset_index()

# Insight: This captures sleep quality impact, not sleep duration alone. Lag-based feature engineering = advanced EDA skill.

C:\Users\Shree\AppData\Local\Temp\ipykernel_8180\2952152406.py:14: DeprecationWarning: DataFrameGroupBy.apply operated on the grouping columns. This behavior is deprecated, and in a future version of pandas the grouping columns will be excluded from the operation. Either pass `include_groups=False` to exclude the groupings or explicitly select the grouping columns after groupby to silence this warning.
  .apply(recovery_efficiency)

           Id           0
0  7007744171  160.885699
1  8053475328  131.964072
2  4558609924   77.571896
3  2320127002   67.177419
4  1644430081   66.272911
5  3977333714   38.738123
6  4388161847   38.187776
7  1503960366   34.554597
8  6962181067   22.333208
9  5577150313   22.260674

In [38]:
# 35. Can we quantify how sensitive each user’s calories are to changes in intensity using a custom regression-like function?
def intensity_sensitivity(group):
    if group['VeryActiveMinutes_x'].std() == 0:
        return np.nan
    
    sensitivity = (
        group['Calories_x'].cov(group['VeryActiveMinutes_x']) /
        group['VeryActiveMinutes_x'].var()
    )
    return sensitivity

intensity_effect = (
    merged_df
    .groupby('Id')
    .apply(intensity_sensitivity)
    .sort_values(ascending=False)
)

intensity_effect.head(10).reset_index()

# Insight: This approximates marginal calorie response without ML.Shows you understand relationships, not just correlations.

C:\Users\Shree\AppData\Local\Temp\ipykernel_8180\690153684.py:15: DeprecationWarning: DataFrameGroupBy.apply operated on the grouping columns. This behavior is deprecated, and in a future version of pandas the grouping columns will be excluded from the operation. Either pass `include_groups=False` to exclude the groupings or explicitly select the grouping columns after groupby to silence this warning.
  .apply(intensity_sensitivity)

           Id           0
0  1844505072  189.215517
1  8792009665  122.543913
2  6117666160   51.671938
3  4702921684   33.265437
4  4319703577   31.516068
5  6775888955   23.224726
6  4020332650   20.456687
7  1644430081   18.579922
8  1927972279   18.090221
9  8877689391   16.237619

In [41]:
# 36. Which users follow similar routines but achieve different outcomes?
routine = merged_df.groupby('Id')['StepTotal'].std()
outcome = merged_df.groupby('Id')['Calories_x'].mean()

pd.concat([routine, outcome], axis=1)

# Insight: Same input, different output → personalization justification.

              StepTotal   Calories_x
Id
1503960366  3052.484201  1816.419355
1624580081  6177.048612  1483.354839
1644430081  4325.478825  2811.300000
1844505072  2712.836854  1573.483871
1927972279  1205.269064  2172.806452
2022484408  2806.994710  2509.967742
2026352035  2977.834815  1540.645161
2320127002  2254.614642  1724.161290
2347167796  4682.093700  2043.444444
2873212765  1514.471585  1916.967742
3372868164  1842.451321  1933.100000
3977333714  3134.141610  1513.666667
4020332650  3369.790624  2385.806452
4057192912  2691.665655  1973.750000
4319703577  3467.055707  2037.677419
4388161847  3325.176826  3087.781250
4445114986  1937.070689  2186.193548
4558609924  2356.961289  2033.258065
4702921684  3547.026242  2987.968750
5553957443  5074.505038  1875.677419
5577150313  3846.985821  3359.633333
6117666160  4887.698154  2261.142857
6290855005  2857.612310  2599.620690
6775888955  3027.802540  2131.769231
6962181067  3941.753387  1982.032258
7007744171  5306.477598  2544.000000
7086361926  3857.093316  2566.354839
8053475328  5440.962055  2945.806452
8253242879  3141.325132  1788.000000
8378563200  3920.015915  3454.343750
8583815059  3401.729275  2732.032258
8792009665  2327.360214  1962.310345
8877689391  5821.315135  3420.258065

In [45]:
# 37. Can we detect users whose behavior changes drastically over time using a rolling-window function?
def behavior_shift(group):
    group = group.sort_values('Date_x')
    
    early = group['TotalSteps'].rolling(7).mean().iloc[:7].mean()
    late = group['TotalSteps'].rolling(7).mean().iloc[-7:].mean()
    
    return late - early

behavior_change = (
    merged_df
    .groupby('Id')
    .apply(behavior_shift)
    .sort_values()
)

behavior_change.head(10).reset_index()

# Insight: This detects lifestyle change, not noise.Same logic applies to churn detection in any industry.

C:\Users\Shree\AppData\Local\Temp\ipykernel_8180\3354546619.py:13: DeprecationWarning: DataFrameGroupBy.apply operated on the grouping columns. This behavior is deprecated, and in a future version of pandas the grouping columns will be excluded from the operation. Either pass `include_groups=False` to exclude the groupings or explicitly select the grouping columns after groupby to silence this warning.
  .apply(behavior_shift)

           Id            0
0  1844505072 -4123.979592
1  8053475328 -3880.142857
2  5577150313 -3846.040816
3  8378563200 -3811.428571
4  8877689391 -3602.591837
5  1624580081 -2734.530612
6  6775888955 -2343.653061
7  1644430081 -1827.408163
8  2022484408 -1823.510204
9  2320127002 -1635.979592

In [47]:
# 38. Can we create a composite “Daily Load Score” using weighted mapping of multiple activity metrics?
def daily_load(row):
    return (
        row['VeryActiveMinutes_x'] * 3 +
        row['FairlyActiveMinutes_x'] * 2 +
        row['LightlyActiveMinutes_x'] * 1
    )

merged_df['daily_load'] = merged_df.apply(daily_load, axis=1)

user_load = (
    merged_df
    .groupby('Id')['daily_load']
    .mean()
    .sort_values(ascending=False)
)

user_load.head(10).reset_index()

# Insight: Weighted feature construction shows domain understanding,not blind aggregation.

           Id  daily_load
0  5577150313  469.600000
1  8877689391  452.774194
2  8053475328  425.612903
3  7007744171  406.384615
4  2022484408  405.032258
5  1503960366  374.387097
6  3372868164  363.550000
7  2873212765  362.548387
8  8378563200  358.000000
9  3977333714  354.000000

In [50]:
# 39. Can we identify users whose activity is driven more by routine than motivation using a custom variance ratio?
def routine_strength(group):
    weekday_means = (
        group
        .groupby(group['Date_x'].dt.day_name())['TotalSteps']
        .mean()
    )
    return 1 / (weekday_means.std() + 1)

routine_index = (
    merged_df
    .groupby('Id')
    .apply(routine_strength)
    .sort_values(ascending=False)
)

routine_index.head(10).reset_index()

# Insight: This measures structural discipline, not effort.Very strong behavioral analytics signal.

C:\Users\Shree\AppData\Local\Temp\ipykernel_8180\1003333402.py:13: DeprecationWarning: DataFrameGroupBy.apply operated on the grouping columns. This behavior is deprecated, and in a future version of pandas the grouping columns will be excluded from the operation. Either pass `include_groups=False` to exclude the groupings or explicitly select the grouping columns after groupby to silence this warning.
  .apply(routine_strength)

           Id   0
0  1503960366 NaN
1  1624580081 NaN
2  1644430081 NaN
3  1844505072 NaN
4  1927972279 NaN
5  2022484408 NaN
6  2026352035 NaN
7  2320127002 NaN
8  2347167796 NaN
9  2873212765 NaN

In [53]:
# 40. Can we design a “Sustainability Score” using a custom function that penalizes over-training and poor sleep?
def sustainability_score(group):
    avg_intensity = group['VeryActiveMinutes_x'].mean()
    avg_sleep = group['TotalMinutesAsleep'].mean()
    sedentary_ratio = group['SedentaryMinutes_x'].mean() / 1440
    
    score = (
        avg_sleep * 0.4 +
        (1 - sedentary_ratio) * 0.3 -
        avg_intensity * 0.01
    )
    return score

sustainability = (
    merged_df
    .groupby('Id')
    .apply(sustainability_score)
    .sort_values(ascending=False)
)

sustainability.head(10).reset_index()

# Insight: This reflects long-term health sustainability, not short-term performance.Composite scoring like this is senior-level EDA.

C:\Users\Shree\AppData\Local\Temp\ipykernel_8180\4046458706.py:17: DeprecationWarning: DataFrameGroupBy.apply operated on the grouping columns. This behavior is deprecated, and in a future version of pandas the grouping columns will be excluded from the operation. Either pass `include_groups=False` to exclude the groupings or explicitly select the grouping columns after groupby to silence this warning.
  .apply(sustainability_score)

           Id           0
0  1844505072  260.847332
1  2026352035  202.626832
2  6117666160  191.629504
3  4319703577  190.772439
4  5553957443  185.320114
5  7086361926  180.947016
6  6962181067  179.133952
7  2347167796  178.741840
8  8378563200  176.883464
9  8792009665  174.336078